# Generated by Django 3.2.7 on 2021-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211006_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='SD201FC', max_length=7, verbose_name='Student code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T12F555', max_length=7, verbose_name='Teacher code'),
        ),
    ]
