# Generated by Django 3.2.7 on 2021-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211013_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S3259D3', max_length=7, verbose_name='Student code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T032C80', max_length=7, verbose_name='Teacher code'),
        ),
    ]
