# Generated by Django 3.2.7 on 2021-10-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211013_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S0F8250', max_length=7, verbose_name='Student code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T8C6E57', max_length=7, verbose_name='Teacher code'),
        ),
    ]
