# Generated by Django 3.2.7 on 2021-10-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211015_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, default='S2B16D6', max_length=7, verbose_name='Student code'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='code',
            field=models.CharField(blank=True, default='T1A22A9', max_length=7, verbose_name='Teacher code'),
        ),
    ]
