# Generated by Django 3.2.7 on 2021-10-06 08:43

from django.db import migrations, models
import django.db.models.deletion
import framework.models.courses
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseORM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('code', models.CharField(blank=True, default='D00274', max_length=6, verbose_name='Code')),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='accounts.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseorm')),
            ],
        ),
        migrations.CreateModel(
            name='SectionORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.moduleorm')),
            ],
        ),
        migrations.CreateModel(
            name='TopicORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('type', models.SmallIntegerField(choices=[(1, 'General'), (2, 'Homework'), (2, 'Quiz')], default=1, verbose_name='Type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.sectionorm')),
            ],
        ),
        migrations.CreateModel(
            name='ResourcesORM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(upload_to=framework.models.courses.get_resource_file_path, verbose_name='File')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.topicorm')),
            ],
        ),
        migrations.CreateModel(
            name='PackageORM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('code', models.CharField(max_length=10)),
                ('courses', models.ManyToManyField(to='courses.CourseORM')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.packageorm')),
            ],
        ),
    ]
