# Generated by Django 3.2.7 on 2021-10-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseorm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorm',
            name='image',
            field=models.ImageField(blank=True, upload_to='courses_images'),
        ),
        migrations.AlterField(
            model_name='courseorm',
            name='code',
            field=models.CharField(blank=True, default='3CCBCB', max_length=6, verbose_name='Code'),
        ),
    ]
