# Generated by Django 3.2.7 on 2021-10-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211013_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorm',
            name='code',
            field=models.CharField(blank=True, default='1C07BE', max_length=6, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='courseorm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images'),
        ),
    ]
